name: Auto Approve Patch Updates PRs

on:
  pull_request:
    types: [opened, labeled]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Auto approve PRs with 'only-patch-updates' label
        if: contains(github.event.pull_request.labels.*.name, 'only-patch-updates')
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
