name: Auto Approve Patch Updates PRs

on:
  pull_request_target:
    types: [opened, labeled]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Auto approve PRs with 'only-patch-updates' label
        run: |
          if [[ "$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")" == *"only-patch-updates"* ]]; then
            gh pr review "$GITHUB_REF" --approve
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
